version: '3'
services:

  postgres-conta-digital:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123dojo"
      POSTGRES_DB: conta-digital
    ports:
      - "15433:5432"
    volumes:
      - contadigital-volume:/var/lib/postgresql/data
    networks:
      - bank-compose-network

  postgres-extrato:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123dojo"
      POSTGRES_DB: extrato
    ports:
      - "15434:5432"
    volumes:
      - extrato-volume:/var/lib/postgresql/data
    networks:
      - bank-compose-network

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - bank-compose-network


  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - bank-compose-network

networks:
  bank-compose-network:
    driver: bridge

volumes:
  contadigital-volume:
  extrato-volume:
